services:
  web:
    build: .
    volumes:
      - .:/app
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "5006:5006"
    environment:
      - DJANGO_SETTINGS_MODULE=AiPlatform.settings
